# Generated by Django 6.0.7 on 2026-08-09 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='menus.dailymenu')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='menus.fooditem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'daily_menu')},
            },
        ),
    ]
