# Generated by Django 6.0.7 on 2026-08-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
