# Generated by Django 6.0.7 on 2026-08-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Menu Title')),
                ('url', models.CharField(max_length=255, verbose_name='(URL/Anchor)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('show_in_desktop', models.BooleanField(default=True, verbose_name='Show on Desktop')),
                ('show_in_mobile', models.BooleanField(default=True, verbose_name='Show on Mobile')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='مرتضی تاجری | توسعه دهنده Backend با Django و Python', max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo_header', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo_footer', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('footer_copyright', models.CharField(default='© 1403 - تمامی حقوق محفوظ است.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
